### PR TITLE
Containter.md Translated & ready for review

### LINKED ISSUE #15: Translate file "container.md"
Notes for contributors, the file can be translated by being aware of and understanding the file you are translating, you must have an understanding of the techniques and the explanation provided by the documentation file, and it must be in Standard Arabic, and the technical terms should be translated as follows:
For example, المتحكمات with the term next to it in English (Controllers)
For example, التهجير and next to it the term in English (Migrations)
And so on
Thank you for your contribution

### PR DESCRIPTION
**Pull request by Mahmoud217TR**
## So I have some words or phrases that are hard to translate appropriately:

**Zero Configuration Resolution:** ميزة عدم الإعداد

**Binding Scoped Singletons:**  محددة النطاق singleton ربط صفوف

**array of typed objects:** مصفوفة أغراض مصرح عن نوعها 

**callback:** للاستدعاء 

## And there are those translations:
**inject:** حقن

**instances:** نُسخ

**Primitives:** قيم أساسية

**If there are any notes or changes, I'll be glad to deal with it.**

### CODE REVIEW

**Comment by karam-mustafa** [comment]
@abdussalam-alali what is your opinion??

**Comment by karam-mustafa** [comment]
@Mahmoud217TR Hi, Thanks a lot for your contribution 
I just want to mention that the template of [dictionary](https://github.com/Syrian-Open-Source/arabic-laravel-docs/blob/9.x/dictionary.md) file was formatted successfully, so if you translate any file please consider that to add any new Phrase into it.

**Comment by Mahmoud217TR** [comment]
Happy to help,
Just waiting for notes about those words or any changes to refactor the file,
Then I would add those words to the dictionary file.

**Review by abdussalam-alali — CHANGES_REQUESTED** [review]
Thanks for your contribution
I'd like to add suggest some documentation improvements 

1. using PHP highlighting for code snippets.
2. In general we translate containers as "حاويات" and Container as "حاوية" 
3. As we deal with OOP I think the correct translation for "Function" or "Method" is "طريقة أو تابع", I prefer "طريقة"
4. I think "البحث عن " or "الحصول على " or "ايجاد" are more accurate than "استبيان" for the word "resolve" in this context.
for example "resolve class" => "ايجاد وتحضير الصف/الصنف"

**Comment by Mahmoud217TR** [comment]
No Problem, I'm on it.
It will be fixed as soon as possible.
I would also refactor my previous translated files with the same words & add PHP highlighting for code snippets for the previous files.

**Comment by Mahmoud217TR** [comment]
I hope this would fix it.
If there is any other suggestions or notes, I'll be happy to apply.

**Pull request merged**
